name: CICD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  PROJECT: "thesis"
  PROJECT_NAME: "Bachelor Thesis Paul Brenker: Relevance of Linter Rules"
  ACTION_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  build_latex:
    name: Build LaTeX
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: *.tex

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Documents
          path: *.pdf

  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 10
    needs:
      - build_latex
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download CV
        uses: actions/download-artifact@v4
        with:
          name: Documents

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v2.${{ github.run_number }}
          name: "Release v0.${{ github.run_number }}"
          files: *.pdf
